### ISSUE TITLE
Create Excel file on the fly

### ISSUE THREAD

**Issue by nakoda** [robotusers/cakephp-excel#11]
Friend It is not an issue, I want to know how i can use this plugin to generate excel file on the fly. I do not want to save file on server. It take data from database and write in spreadsheet and available user for download

Your quick response is appricited

**Comment by robertpustulka** [comment]
Hi. Thanks.

You just need to fill a table with data, set your output file and call `writeSpreadsheet()` on a table. Or you can use a manager with dynamic tables as described here: https://github.com/robotusers/cakephp-excel#working-with-different-tables.

Then you need to attach your output file to the response.

**Comment by nakoda** [comment]
Thanks for quick response. 

Its seems we can use this in table files. Is there any method available which can use directly from controller and output to view.
 
Also still i am not clear how things will come together. Suppose i get all blog data using find() method [with associated table data]. Now how to write this data on spreadsheet and make it  available for download.

**Comment by robertpustulka** [comment]
If you feel anything is missing in the plugin, feel free to send a PR.

Although this plugin is just an ORM wrapper for PHP Spreadsheet lib. If you need to have some sort of controller-view integration that's just up to you.

**Comment by thiagoreri** [comment]
You just need to fill a table with data, set your output file and call writeSpreadsheet() on a table.

Can you give us an example?
