### ISSUE TITLE
Error: The datasource configuration excel was not found in config\app.php

### ISSUE THREAD

**Issue by michelmotta** [robotusers/cakephp-excel#12]
Hi,
I'm following the first steps to get the plugin working, but I'm receiving an error message `Error: The datasource configuration excel was not found in config\app.php. ` Could someone help me to understand what is wrong?

This is my snippet code 

```
use Robotusers\Excel\Registry;

...

$registry = Registry::instance();
$table = $registry->get($filePath, 'Clientes');
$row = $table->find()->first()->toArray();
print_r($row);
```

**Comment by robertpustulka** [comment]
@michelmotta Hi,

Have you loaded the bootstrap file of a plugin?

```sh
bin/cake plugin load Robotusers/Excel -b
```

or 
```php
//boostrap.php
Plugin::load('Robotusers/Excel', [
    'bootstrap' => true,
]);
```

Otherwise you need to provide your own `excel` connection for tmp db.

**Comment by robertpustulka** [comment]
@michelmotta have you been able to set things up?

**Comment by bilz003** [comment]
@robertpustulka I am having the same issue and I have loaded the plugin in the bootstrap.php file.

@michelmotta How did you solved your issue?

**Comment by robertpustulka** [comment]
Do you have sqlite installed? It is required for temp connection. Otherwise you need to provide your own connection. See: https://github.com/robotusers/cakephp-excel/blob/master/config/bootstrap.php

**Comment by bilz003** [comment]
Yes I have, sqlite 3 installed. 

SQLite 3.x driver for PDO        | Wez Furlong
SQLite3                                    | Scott MacVicar, Ilia Alshanetsky, Brad Dewar

@robertpustulka still can't figure out the issue :(

**Comment by robertpustulka** [comment]
Are you sure you are loading plugin's bootstrap file? Can you show the code?
