### ISSUE TITLE
"The plugin class Robotusers\Excel\Plugin cannot be found. Ensure your autoloader is correct."

### ISSUE THREAD

**Issue by x-wf** [robotusers/cakephp-excel#13]
Hello,
I've followed your steps to get this plugin working with CakePHP 3.6, running PHP 7.2, those two first steps to get this excel plugin working.

All I keep getting is 
**The plugin class `Robotusers\Excel\Plugin` cannot be found. Ensure your autoloader is correct.**

I executed
`composer require robotusers/cakephp-excel`

Added to config/bootstrap.php:
`
Plugin::load('Robotusers/Excel', [
    'bootstrap' => true,
]);
`

In my src/Application.php
```
public function bootstrap()
    {
        // Call parent to load bootstrap from files.
        parent::bootstrap();
        $this->addPlugin('Robotusers/Excel');
    }
```

In my controller:
```
public $helpers = ['Cewi/Excel.Excel'];

public function excel()
        {
            $registry = Registry::instance();
            $table = $registry->get('records.xlsx', 'efproducts_products', [
                'primaryKey' => 'id',
                'columnMap' => [
                    'A' => 'project_name',
                    'B' => 'ef_type',
                    'C' => 'product_description'
                ]
            ]);
        }

```

But I keep getting the error explained above.
What am I missing?

Thank you,
James

**Comment by robertpustulka** [comment]
Hi,
Thanks for the report!

BTW looks like you're trying to load the plugin twice.
Looks like I haven't released the recent changes with support for `Plugin` class yet...

Please remove `$this->addPlugin('Robotusers/Excel');` from your app's bootstrap method.

**Comment by robertpustulka** [comment]
[0.6.0](https://github.com/robotusers/cakephp-excel/releases/tag/0.6.0) has been released.
